name: tup_ar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  go_router: ^11.1.2
  get_it: ^7.6.4
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  flutter_unity_widget: ^2022.2.1
  permission_handler: ^11.0.1
  google_sign_in: ^6.1.6
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.14.0
  url_launcher: ^6.1.14
  tup_ar_core:
    git:
      url: https://github.com/markcabalona/tup-ar-core
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
